@startuml
left to right direction
package "Rental Car Booking"{
    class "<<Application>>\nRental Car Booking" as rentalCarBooking{}

    class "<<Resource>>\nUsers" as ResourceUsers{
        <<GET>> +register():User
        <<POST>> +login():User
        <<GET>> +logout():void
    }

    class "<<Resource>>\nUser" as ResourceUser {
        <<DELETE>> -deleteUser(): void
    }

    class "<<Representation>>\nUser" as RepresentationUser {
        -name
        -telephone
        -email
        -password
        -balance
        -role
        -createAt
    }


    

    class "<<Resource>>\nRentings" as ResourceRentings{
        <<GET>> 
        <<POST>> 
        <<GET>>
    }

    class "<<Resource>>\nRenting" as ResourceRenting {
        
    }

    class "<<Representation>>\nRenting" as RepresentationRenting {
        -rentDate
        -rentTo
        -user
        -carProvider
        -createAt
        -returned
    }


    

    class "<<Resource>>\nCarProviders" as ResourceCarProviders{
        <<GET>> 
        <<POST>> 
        <<GET>> 
    }

    class "<<Resource>>\nCarProvider" as ResourceCarProvider {
        <<DELETE>> 
    }

    class "<<Representation>>\nCarProvider" as RepresentationCarProvider {
        -name
        -address
        -telephone
        -price
    }



}

rentalCarBooking ..> ResourceUsers:"/Users\n<<Path>>"
ResourceUsers ..> ResourceUser: "/{:id}\n<<Path>>"
ResourceUser ..> RepresentationUser: "<<use>>"

rentalCarBooking ..> ResourceRentings:"/Rentings\n<<Path>>"
ResourceRentings ..> ResourceRenting: "/{:id}\n<<Path>>"
ResourceRenting ..> RepresentationRenting: "<<use>>"

rentalCarBooking ..> ResourceCarProviders:"/CarProviders\n<<Path>>"
ResourceCarProviders ..> ResourceCarProvider: "/{:id}\n<<Path>>"
ResourceCarProvider ..> RepresentationCarProvider: "<<use>>"

@enduml