@startuml Get Car Providers (GET)

header Sample RentalCarBooking Sequence Diagram
footer Page %page% of %lastpage%
title "Get Car Providers (GET)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:carProviders" as routerCarProvider
participant "<<controllers>>\n:carProvider" as controllersCarProvider
participant "<<model>>\n:CarProvider" as modelCarProvider
database "<<MongoDB>>\n:carproviders" as CarProviderDatabase

client->server ++:req.get('/api/v1/carproviders')
server->routerCarProvider ++:app.use('/api/v1/carproviders', carProviders)
routerCarProvider -> controllersCarProvider ++: getCarProviders()
controllersCarProvider->modelCarProvider ++: find()
modelCarProvider ->CarProviderDatabase ++: CarProviderSchema
CarProviderDatabase --> modelCarProvider --: carProviders
controllersCarProvider <-- modelCarProvider --: carProviders
controllersCarProvider->client --: response.status(200).json({success: true, count: carProviders.length, data: carProviders})

@enduml
